export type MenuTag = {
  id: number;
  name: string;
  code: string;
};

/** 02_dummy_data.sql menu_tags 기준 */
export const MENU_TAGS: MenuTag[] = [
  { id: 1, name: "후라이드치킨", code: "FRIED_CHICKEN" },
  { id: 2, name: "양념치킨", code: "SEASONED_CHICKEN" },
  { id: 3, name: "간장치킨", code: "SOY_CHICKEN" },
  { id: 4, name: "순살치킨", code: "BONELESS_CHICKEN" },
  { id: 5, name: "파닭", code: "GREEN_ONION_CHICKEN" },
  { id: 6, name: "햄버거", code: "BURGER" },
  { id: 7, name: "치킨버거", code: "CHICKEN_BURGER" },
  { id: 8, name: "감자튀김", code: "FRENCH_FRIES" },
  { id: 9, name: "핫도그", code: "HOTDOG" },
  { id: 10, name: "프랜차이즈세트", code: "FRANCHISE_SET" },
  { id: 11, name: "피자", code: "PIZZA" },
  { id: 12, name: "파스타", code: "PASTA" },
  { id: 13, name: "리조또", code: "RISOTTO" },
  { id: 14, name: "스테이크", code: "STEAK" },
  { id: 15, name: "필라프", code: "PILAF" },
  { id: 16, name: "치즈스틱", code: "CHEESE_STICK" },
  { id: 17, name: "갈릭브레드", code: "GARLIC_BREAD" },
  { id: 18, name: "짜장면", code: "BLACK_BEAN_NOODLE" },
  { id: 19, name: "짬뽕", code: "JJAMPPONG" },
  { id: 20, name: "탕수육", code: "TANGSUYUK" },
  { id: 21, name: "볶음밥", code: "FRIED_RICE" },
  { id: 22, name: "군만두", code: "MANDU" },
  { id: 23, name: "마파두부", code: "MAPO_TOFU" },
  { id: 24, name: "깐풍기", code: "KANPUNGGI" },
  { id: 25, name: "국밥", code: "GUKBAP" },
  { id: 26, name: "찜닭", code: "JJIMDAK" },
  { id: 27, name: "제육볶음", code: "JEYUK" },
  { id: 28, name: "된장찌개", code: "DOENJANG" },
  { id: 29, name: "순두부찌개", code: "SUNDUBU" },
  { id: 30, name: "갈비탕", code: "GALBITANG" },
  { id: 31, name: "비빔밥", code: "BIBIMBAP" },
  { id: 32, name: "초밥", code: "SUSHI" },
  { id: 33, name: "라멘", code: "RAMEN" },
  { id: 34, name: "돈까스", code: "TONKATSU" },
  { id: 35, name: "우동", code: "UDON" },
  { id: 36, name: "규동", code: "GYUDON" },
  { id: 37, name: "카츠동", code: "KATSUDON" },
  { id: 38, name: "족발", code: "JOKBAL" },
  { id: 39, name: "보쌈", code: "BOSSAM" },
  { id: 40, name: "막국수", code: "MAKGUKSU" },
  { id: 41, name: "냉채족발", code: "COLD_JOKBAL" },
  { id: 42, name: "삼겹살", code: "SAMGYEOPSAL" },
  { id: 43, name: "닭발", code: "CHICKEN_FEET" },
  { id: 44, name: "곱창", code: "GOPCHANG" },
  { id: 45, name: "곱도리탕", code: "GOPDORITANG" },
  { id: 46, name: "오돌뼈", code: "ODOLBBYEO" },
  { id: 47, name: "주먹밥", code: "RICE_BALL" },
  { id: 48, name: "떡볶이", code: "TTEOKBOKKI" },
  { id: 49, name: "김밥", code: "KIMBAP" },
  { id: 50, name: "순대", code: "SUNDAE" },
  { id: 51, name: "튀김", code: "TWIGIM" },
  { id: 52, name: "라면", code: "RAMYEON" },
  { id: 53, name: "어묵", code: "EOMUK" },
  { id: 54, name: "커피", code: "COFFEE" },
  { id: 55, name: "케이크", code: "CAKE" },
  { id: 56, name: "크로플", code: "CROFFLE" },
  { id: 57, name: "마카롱", code: "MACARON" },
  { id: 58, name: "빙수", code: "BINGSU" },
  { id: 59, name: "스무디", code: "SMOOTHIE" },
  { id: 60, name: "콜라", code: "COLA" },
  { id: 61, name: "사이다", code: "CIDER" },
  { id: 62, name: "공기밥", code: "RICE" },
  { id: 63, name: "치킨무", code: "PICKLED_RADISH" },
  { id: 64, name: "소스추가", code: "EXTRA_SAUCE" },
];
